/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ProfileController;
import javax.swing.JOptionPane;

/**
 *
 * @author ahmed_ishraq <https://github.com/ahmedishraq>
 */
public class Admin_TaxCalculationView1 extends javax.swing.JFrame {

    /**
     * Creates new form User_HomeView
     */
    public Admin_TaxCalculationView1() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Profile");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title_L = new javax.swing.JLabel();
        profile_L = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        logout_B = new javax.swing.JButton();
        home_B = new javax.swing.JButton();
        username_L = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25), new java.awt.Dimension(32767, 25));
        name_L = new javax.swing.JLabel();
        name_TF1 = new javax.swing.JTextField();
        id_TF = new javax.swing.JTextField();
        name_L1 = new javax.swing.JLabel();
        id_TF1 = new javax.swing.JTextField();
        name_L2 = new javax.swing.JLabel();
        name_L3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        name_L4 = new javax.swing.JLabel();
        salaryIncome_TF = new javax.swing.JTextField();
        name_L5 = new javax.swing.JLabel();
        professionIncome_TF = new javax.swing.JTextField();
        name_L6 = new javax.swing.JLabel();
        bankInterest_TF = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        name_L7 = new javax.swing.JLabel();
        name_TF2 = new javax.swing.JTextField();
        name_L8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        name_L9 = new javax.swing.JLabel();
        ti_TF1 = new javax.swing.JTextField();
        name_L10 = new javax.swing.JLabel();
        TF1 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        name_L11 = new javax.swing.JLabel();
        ti_TF2 = new javax.swing.JTextField();
        TF2 = new javax.swing.JTextField();
        name_L12 = new javax.swing.JLabel();
        ti_TF3 = new javax.swing.JTextField();
        TF3 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        name_L13 = new javax.swing.JLabel();
        ti_TF4 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        taxableIncome_L = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        calculatetax_B = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        title_L.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        title_L.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_L.setText("Compact Taxing");

        profile_L.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        profile_L.setText("My Profile");

        logout_B.setText("Logout");
        logout_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_BActionPerformed(evt);
            }
        });

        home_B.setText("Home");
        home_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_BActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addGap(91, 91, 91))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(208, Short.MAX_VALUE)
                        .addComponent(title_L, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(profile_L)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(home_B)
                        .addGap(18, 18, 18)
                        .addComponent(logout_B)))
                .addGap(110, 110, 110))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(title_L)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profile_L)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(logout_B)
                        .addComponent(home_B)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        username_L.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        username_L.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        name_L.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        name_L.setText("Name of the Assessee:");

        name_TF1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        name_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_TF1ActionPerformed(evt);
            }
        });

        id_TF.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        id_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_TFActionPerformed(evt);
            }
        });

        name_L1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        name_L1.setText("Address:");

        id_TF1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        id_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_TF1ActionPerformed(evt);
            }
        });

        name_L2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        name_L2.setText("Assessment Year:");

        name_L3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        name_L3.setText("To Sum Up:");

        name_L4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        name_L4.setText("Income From Salary");

        salaryIncome_TF.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        salaryIncome_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        salaryIncome_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryIncome_TFActionPerformed(evt);
            }
        });

        name_L5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        name_L5.setText("Income From Profession");

        professionIncome_TF.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        professionIncome_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        professionIncome_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professionIncome_TFActionPerformed(evt);
            }
        });

        name_L6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        name_L6.setText("Bank Interest");

        bankInterest_TF.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        bankInterest_TF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        bankInterest_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankInterest_TFActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Calculate Taxable Income");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        name_L7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        name_L7.setText("TIN:");

        name_TF2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        name_TF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_TF2ActionPerformed(evt);
            }
        });

        name_L8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        name_L8.setText("Calculation Of Tax");

        name_L9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        name_L9.setText("Taxable Income");

        ti_TF1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ti_TF1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ti_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ti_TF1ActionPerformed(evt);
            }
        });

        name_L10.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        name_L10.setText("Taxableon 1st");

        TF1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        TF1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TF1.setText("300000");
        TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF1ActionPerformed(evt);
            }
        });

        name_L11.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        name_L11.setText("Tax On Next");

        ti_TF2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ti_TF2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ti_TF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ti_TF2ActionPerformed(evt);
            }
        });

        TF2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        TF2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TF2.setText("100000");
        TF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF2ActionPerformed(evt);
            }
        });

        name_L12.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        name_L12.setText("Tax On Next");

        ti_TF3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ti_TF3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ti_TF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ti_TF3ActionPerformed(evt);
            }
        });

        TF3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        TF3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TF3.setText("300000");
        TF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF3ActionPerformed(evt);
            }
        });

        name_L13.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        name_L13.setText("Tax On Balance");

        ti_TF4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ti_TF4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ti_TF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ti_TF4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel1.setText("Nil");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setText("@");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setText("@");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setText("@");

        taxableIncome_L.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        taxableIncome_L.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        L1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        L1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        L2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        L2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        L3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        L3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        calculatetax_B.setText("Calculate Tax");
        calculatetax_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatetax_BActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel8.setText("5%");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel9.setText("10%");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel10.setText("15%");

        L4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        L4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(445, 445, 445)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(username_L, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addComponent(name_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(name_L1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(name_L2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(name_L3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(name_L7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(name_L4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(name_L5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(name_L6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(name_L9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(name_L10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGap(94, 94, 94)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addGap(52, 52, 52)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(id_TF)
                                            .addComponent(name_TF1)
                                            .addComponent(id_TF1)
                                            .addComponent(salaryIncome_TF)
                                            .addComponent(professionIncome_TF)
                                            .addComponent(bankInterest_TF)
                                            .addComponent(name_TF2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(ti_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18))
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(26, 26, 26)))
                                                        .addComponent(jLabel1))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(4, 4, 4)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(calculatetax_B)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(L4))
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(L2)
                                                                .addComponent(L1)
                                                                .addComponent(L3)
                                                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                    .addComponent(taxableIncome_L, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addGap(296, 296, 296))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(230, 230, 230)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TF3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(ti_TF3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jSeparator7)
                                                        .addComponent(name_L11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jSeparator8)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(name_L12, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(245, 245, 245))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                            .addComponent(name_L13, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(ti_TF4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(9, 9, 9)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(229, 229, 229)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(TF2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(ti_TF2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel4)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jSeparator4)
                                                        .addComponent(name_L8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(193, 193, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name_L)
                            .addComponent(name_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name_L7)
                            .addComponent(name_TF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name_L1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name_L2)
                            .addComponent(id_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(name_L3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salaryIncome_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name_L4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(professionIncome_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name_L5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bankInterest_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name_L6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(taxableIncome_L))
                        .addGap(46, 46, 46)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name_L8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name_L9)
                            .addComponent(ti_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name_L10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ti_TF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(L1)
                                    .addComponent(TF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(name_L11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ti_TF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(L2)
                                .addComponent(jLabel9))
                            .addComponent(name_L12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ti_TF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(L3)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(calculatetax_B)
                                    .addComponent(L4))
                                .addGap(0, 65, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(name_L13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(610, 610, 610)
                        .addComponent(username_L)
                        .addGap(155, 155, 155)))
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logout_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_BActionPerformed
        int rst = JOptionPane.showConfirmDialog(null, "Are you sure want to logout");
        if (rst == 1 || rst == 2){
            
        }
        else{
            User_LoginView user = new User_LoginView();
            setVisible(false);
            user.setVisible(true);
        }
    }//GEN-LAST:event_logout_BActionPerformed

    private void home_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_BActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_home_BActionPerformed

    private void id_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_TFActionPerformed

    private void name_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_TF1ActionPerformed

    private void id_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_TF1ActionPerformed

    private void salaryIncome_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryIncome_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryIncome_TFActionPerformed

    private void professionIncome_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professionIncome_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_professionIncome_TFActionPerformed

    private void bankInterest_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankInterest_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bankInterest_TFActionPerformed

    private void name_TF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_TF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_TF2ActionPerformed

    private void ti_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ti_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ti_TF1ActionPerformed

    private void TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF1ActionPerformed

    private void TF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF2ActionPerformed

    private void ti_TF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ti_TF3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ti_TF3ActionPerformed

    private void TF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF3ActionPerformed

    private void ti_TF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ti_TF4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ti_TF4ActionPerformed

    private void ti_TF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ti_TF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ti_TF2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            int salary_income = Integer.parseInt(salaryIncome_TF.getText());
            int profession_income = Integer.parseInt(professionIncome_TF.getText());
            int bank_interest = Integer.parseInt(bankInterest_TF.getText());
            int taxable_income = salary_income + profession_income + bank_interest;
            String ti = String.valueOf(taxable_income);
            ti_TF1.setText(ti);
            taxableIncome_L.setText(ti);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void calculatetax_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatetax_BActionPerformed
        try{
            int tf1 = Integer.parseInt(TF1.getText());
            int tf2 = Integer.parseInt(TF2.getText());
            int tf3 = Integer.parseInt(TF3.getText());
            
            int ti1 = Integer.parseInt(ti_TF1.getText());
//            int ti2 = Integer.parseInt(ti_TF2.getText());
//            int ti3 = Integer.parseInt(ti_TF3.getText());
//            int ti4 = Integer.parseInt(ti_TF4.getText());
            int ti2 = ti1 - tf1;
            int ti3 = ti2 - tf2;
            int ti4 = ti3 - tf3;
            
            // convert string and put them into the text field 
            String tii2 = String.valueOf(ti2);
            String tii3 = String.valueOf(ti3);
            String tii4 = String.valueOf(ti4);
            
            ti_TF2.setText(tii2);
            ti_TF3.setText(tii3);
            ti_TF4.setText(tii4);
            
            
            // result setting
            int r_tf1 = (tf2*5)/100;
            int r_tf2 = (tf3*10)/100;
            int r_tf3 = (ti4*15)/100;
            int tax = r_tf1 + r_tf2 + r_tf3;
            
            String rr_tf1 = String.valueOf(r_tf1);
            String rr_tf2 = String.valueOf(r_tf2);
            String rr_tf3 = String.valueOf(r_tf3);
            String rr_tax = String.valueOf(tax);
            
            L1.setText(rr_tf1);
            L2.setText(rr_tf2);
            L3.setText(rr_tf3);
            L4.setText(rr_tax);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_calculatetax_BActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_TaxCalculationView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_TaxCalculationView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_TaxCalculationView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_TaxCalculationView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_TaxCalculationView1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JTextField TF1;
    private javax.swing.JTextField TF2;
    private javax.swing.JTextField TF3;
    private javax.swing.JTextField bankInterest_TF;
    private javax.swing.JButton calculatetax_B;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton home_B;
    private javax.swing.JTextField id_TF;
    private javax.swing.JTextField id_TF1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton logout_B;
    private javax.swing.JLabel name_L;
    private javax.swing.JLabel name_L1;
    private javax.swing.JLabel name_L10;
    private javax.swing.JLabel name_L11;
    private javax.swing.JLabel name_L12;
    private javax.swing.JLabel name_L13;
    private javax.swing.JLabel name_L2;
    private javax.swing.JLabel name_L3;
    private javax.swing.JLabel name_L4;
    private javax.swing.JLabel name_L5;
    private javax.swing.JLabel name_L6;
    private javax.swing.JLabel name_L7;
    private javax.swing.JLabel name_L8;
    private javax.swing.JLabel name_L9;
    private javax.swing.JTextField name_TF1;
    private javax.swing.JTextField name_TF2;
    private javax.swing.JTextField professionIncome_TF;
    private javax.swing.JLabel profile_L;
    private javax.swing.JTextField salaryIncome_TF;
    private javax.swing.JLabel taxableIncome_L;
    private javax.swing.JTextField ti_TF1;
    private javax.swing.JTextField ti_TF2;
    private javax.swing.JTextField ti_TF3;
    private javax.swing.JTextField ti_TF4;
    private javax.swing.JLabel title_L;
    private javax.swing.JLabel username_L;
    // End of variables declaration//GEN-END:variables
}
