/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author ahmed_ishraq <https://github.com/ahmedishraq>
 */
public class User_ProfileView extends javax.swing.JFrame {

    /**
     * Creates new form User_HomeView
     */
    public User_ProfileView() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Profile");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title_L = new javax.swing.JLabel();
        profile_L = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        logout_B = new javax.swing.JButton();
        home_B = new javax.swing.JButton();
        username_L = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25), new java.awt.Dimension(32767, 25));
        jSeparator2 = new javax.swing.JSeparator();
        name_L = new javax.swing.JLabel();
        name_TF = new javax.swing.JTextField();
        name_TF1 = new javax.swing.JTextField();
        name_TF2 = new javax.swing.JTextField();
        name_L1 = new javax.swing.JLabel();
        utin_L = new javax.swing.JLabel();
        ut1_TF = new javax.swing.JTextField();
        tin_L = new javax.swing.JLabel();
        ut2_TF = new javax.swing.JTextField();
        ut3_TF = new javax.swing.JTextField();
        ut4_TF = new javax.swing.JTextField();
        ut5_TF = new javax.swing.JTextField();
        ut6_TF = new javax.swing.JTextField();
        ut7_TF = new javax.swing.JTextField();
        ut8_TF = new javax.swing.JTextField();
        ut9_TF = new javax.swing.JTextField();
        ut10_TF = new javax.swing.JTextField();
        ut11_TF = new javax.swing.JTextField();
        ut12_TF = new javax.swing.JTextField();
        ut7_TF1 = new javax.swing.JTextField();
        ut8_TF1 = new javax.swing.JTextField();
        ut9_TF1 = new javax.swing.JTextField();
        ut10_TF1 = new javax.swing.JTextField();
        ut11_TF1 = new javax.swing.JTextField();
        ut12_TF1 = new javax.swing.JTextField();
        ut1_TF1 = new javax.swing.JTextField();
        ut2_TF1 = new javax.swing.JTextField();
        ut3_TF1 = new javax.swing.JTextField();
        ut4_TF1 = new javax.swing.JTextField();
        ut5_TF1 = new javax.swing.JTextField();
        ut6_TF1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        title_L.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        title_L.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_L.setText("Compact Taxing");

        profile_L.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        profile_L.setText("My Profile");

        logout_B.setText("Logout");
        logout_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_BActionPerformed(evt);
            }
        });

        home_B.setText("Home");
        home_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_BActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(profile_L)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(home_B)
                .addGap(18, 18, 18)
                .addComponent(logout_B)
                .addGap(110, 110, 110))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addGap(91, 91, 91))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(title_L, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(title_L)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profile_L)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(logout_B)
                        .addComponent(home_B)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        username_L.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        username_L.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        name_L.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        name_L.setText("Name of the Assessee:");

        name_TF.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        name_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_TFActionPerformed(evt);
            }
        });

        name_TF1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        name_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_TF1ActionPerformed(evt);
            }
        });

        name_TF2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        name_TF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_TF2ActionPerformed(evt);
            }
        });

        name_L1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        name_L1.setText("National ID No (If any):");

        utin_L.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        utin_L.setText("UTIN (If any):");

        ut1_TF.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ut1_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ut1_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ut1_TFActionPerformed(evt);
            }
        });

        tin_L.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tin_L.setText("TIN:");

        ut2_TF.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ut2_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ut2_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ut2_TFActionPerformed(evt);
            }
        });

        ut3_TF.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ut3_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ut3_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ut3_TFActionPerformed(evt);
            }
        });

        ut4_TF.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ut4_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ut4_TF.setText("-");
        ut4_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ut4_TFActionPerformed(evt);
            }
        });

        ut5_TF.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ut5_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ut5_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ut5_TFActionPerformed(evt);
            }
        });

        ut6_TF.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ut6_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ut6_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ut6_TFActionPerformed(evt);
            }
        });

        ut7_TF.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ut7_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ut7_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ut7_TFActionPerformed(evt);
            }
        });

        ut8_TF.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ut8_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ut8_TF.setText("-");
        ut8_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ut8_TFActionPerformed(evt);
            }
        });

        ut9_TF.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ut9_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ut9_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ut9_TFActionPerformed(evt);
            }
        });

        ut10_TF.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ut10_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ut10_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ut10_TFActionPerformed(evt);
            }
        });

        ut11_TF.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ut11_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ut11_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ut11_TFActionPerformed(evt);
            }
        });

        ut12_TF.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ut12_TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ut12_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ut12_TFActionPerformed(evt);
            }
        });

        ut7_TF1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ut7_TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ut7_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ut7_TF1ActionPerformed(evt);
            }
        });

        ut8_TF1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ut8_TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ut8_TF1.setText("-");
        ut8_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ut8_TF1ActionPerformed(evt);
            }
        });

        ut9_TF1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ut9_TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ut9_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ut9_TF1ActionPerformed(evt);
            }
        });

        ut10_TF1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ut10_TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ut10_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ut10_TF1ActionPerformed(evt);
            }
        });

        ut11_TF1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ut11_TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ut11_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ut11_TF1ActionPerformed(evt);
            }
        });

        ut12_TF1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ut12_TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ut12_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ut12_TF1ActionPerformed(evt);
            }
        });

        ut1_TF1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ut1_TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ut1_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ut1_TF1ActionPerformed(evt);
            }
        });

        ut2_TF1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ut2_TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ut2_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ut2_TF1ActionPerformed(evt);
            }
        });

        ut3_TF1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ut3_TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ut3_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ut3_TF1ActionPerformed(evt);
            }
        });

        ut4_TF1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ut4_TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ut4_TF1.setText("-");
        ut4_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ut4_TF1ActionPerformed(evt);
            }
        });

        ut5_TF1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ut5_TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ut5_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ut5_TF1ActionPerformed(evt);
            }
        });

        ut6_TF1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        ut6_TF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ut6_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ut6_TF1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username_L, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(445, 445, 445)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(name_L1)
                                    .addComponent(name_L)
                                    .addComponent(utin_L, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tin_L, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(name_TF1)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(ut1_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ut2_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ut3_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ut4_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ut5_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ut6_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ut7_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ut8_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ut9_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ut10_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ut11_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ut12_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(name_TF2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ut1_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ut2_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ut3_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ut4_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ut5_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ut6_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ut7_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ut8_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ut9_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ut10_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ut11_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ut12_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                        .addComponent(name_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name_L)
                            .addComponent(name_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name_TF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name_L1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(utin_L)
                            .addComponent(ut1_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ut2_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ut3_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ut4_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ut5_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ut6_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ut7_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ut8_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ut9_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ut10_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ut11_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ut12_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ut1_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ut2_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ut3_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ut4_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ut5_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ut6_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ut7_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ut8_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ut9_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ut10_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ut11_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ut12_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tin_L))
                        .addGap(247, 247, 247)
                        .addComponent(username_L)
                        .addGap(102, 102, 102)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(name_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logout_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_BActionPerformed
        int rst = JOptionPane.showConfirmDialog(null, "Are you sure want to logout");
        if (rst == 1 || rst == 2){
            
        }
        else{
            User_LoginView user = new User_LoginView();
            setVisible(false);
            user.setVisible(true);
        }
    }//GEN-LAST:event_logout_BActionPerformed

    private void home_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_home_BActionPerformed

    private void name_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_TFActionPerformed

    private void name_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_TF1ActionPerformed

    private void name_TF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_TF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_TF2ActionPerformed

    private void ut1_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ut1_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ut1_TFActionPerformed

    private void ut2_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ut2_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ut2_TFActionPerformed

    private void ut3_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ut3_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ut3_TFActionPerformed

    private void ut4_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ut4_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ut4_TFActionPerformed

    private void ut5_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ut5_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ut5_TFActionPerformed

    private void ut6_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ut6_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ut6_TFActionPerformed

    private void ut7_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ut7_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ut7_TFActionPerformed

    private void ut8_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ut8_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ut8_TFActionPerformed

    private void ut9_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ut9_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ut9_TFActionPerformed

    private void ut10_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ut10_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ut10_TFActionPerformed

    private void ut11_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ut11_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ut11_TFActionPerformed

    private void ut12_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ut12_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ut12_TFActionPerformed

    private void ut7_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ut7_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ut7_TF1ActionPerformed

    private void ut8_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ut8_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ut8_TF1ActionPerformed

    private void ut9_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ut9_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ut9_TF1ActionPerformed

    private void ut10_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ut10_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ut10_TF1ActionPerformed

    private void ut11_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ut11_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ut11_TF1ActionPerformed

    private void ut12_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ut12_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ut12_TF1ActionPerformed

    private void ut1_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ut1_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ut1_TF1ActionPerformed

    private void ut2_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ut2_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ut2_TF1ActionPerformed

    private void ut3_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ut3_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ut3_TF1ActionPerformed

    private void ut4_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ut4_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ut4_TF1ActionPerformed

    private void ut5_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ut5_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ut5_TF1ActionPerformed

    private void ut6_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ut6_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ut6_TF1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_ProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_ProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_ProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_ProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_ProfileView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton home_B;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton logout_B;
    private javax.swing.JLabel name_L;
    private javax.swing.JLabel name_L1;
    private javax.swing.JTextField name_TF;
    private javax.swing.JTextField name_TF1;
    private javax.swing.JTextField name_TF2;
    private javax.swing.JLabel profile_L;
    private javax.swing.JLabel tin_L;
    private javax.swing.JLabel title_L;
    private javax.swing.JLabel username_L;
    private javax.swing.JTextField ut10_TF;
    private javax.swing.JTextField ut10_TF1;
    private javax.swing.JTextField ut11_TF;
    private javax.swing.JTextField ut11_TF1;
    private javax.swing.JTextField ut12_TF;
    private javax.swing.JTextField ut12_TF1;
    private javax.swing.JTextField ut1_TF;
    private javax.swing.JTextField ut1_TF1;
    private javax.swing.JTextField ut2_TF;
    private javax.swing.JTextField ut2_TF1;
    private javax.swing.JTextField ut3_TF;
    private javax.swing.JTextField ut3_TF1;
    private javax.swing.JTextField ut4_TF;
    private javax.swing.JTextField ut4_TF1;
    private javax.swing.JTextField ut5_TF;
    private javax.swing.JTextField ut5_TF1;
    private javax.swing.JTextField ut6_TF;
    private javax.swing.JTextField ut6_TF1;
    private javax.swing.JTextField ut7_TF;
    private javax.swing.JTextField ut7_TF1;
    private javax.swing.JTextField ut8_TF;
    private javax.swing.JTextField ut8_TF1;
    private javax.swing.JTextField ut9_TF;
    private javax.swing.JTextField ut9_TF1;
    private javax.swing.JLabel utin_L;
    // End of variables declaration//GEN-END:variables
}
