/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.HomeController;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ahmed_ishraq <https://github.com/ahmedishraq>
 */
public class User_DocumentsView extends javax.swing.JFrame {

    /**
     * Creates new form User_HomeView
     */
    public User_DocumentsView() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Home");
        username_L.setText("Hi Ishraq,");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title_L = new javax.swing.JLabel();
        home_L = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        logout_B = new javax.swing.JButton();
        hone_B = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        myprofile_B = new javax.swing.JButton();
        mydoc_B = new javax.swing.JButton();
        appoinment_B = new javax.swing.JButton();
        receipt_B = new javax.swing.JButton();
        payment_B = new javax.swing.JButton();
        title2_L = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        username_L = new javax.swing.JLabel();
        salary_L = new javax.swing.JLabel();
        s_upload_B = new javax.swing.JButton();
        bank_L2 = new javax.swing.JLabel();
        b_upload_B2 = new javax.swing.JButton();
        chalan_L3 = new javax.swing.JLabel();
        c_upload_B3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        title_L.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        title_L.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_L.setText("Compact Taxing");

        home_L.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        home_L.setText("Home");

        logout_B.setText("Logout");
        logout_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_BActionPerformed(evt);
            }
        });

        hone_B.setText("Home");
        hone_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hone_BActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(home_L)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hone_B)
                            .addGap(18, 18, 18)
                            .addComponent(logout_B)
                            .addGap(19, 19, 19)))
                    .addComponent(title_L, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(title_L)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(home_L)
                    .addComponent(logout_B)
                    .addComponent(hone_B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        myprofile_B.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        myprofile_B.setText("My Profile");
        myprofile_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myprofile_BActionPerformed(evt);
            }
        });

        mydoc_B.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mydoc_B.setText("My Documents");

        appoinment_B.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        appoinment_B.setText("Appoinment");

        receipt_B.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        receipt_B.setText("Receipt\n");
        receipt_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receipt_BActionPerformed(evt);
            }
        });

        payment_B.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        payment_B.setText("Payment");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(payment_B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(myprofile_B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mydoc_B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(appoinment_B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(receipt_B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(myprofile_B, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(mydoc_B, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(appoinment_B, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(receipt_B, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(payment_B, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        title2_L.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        title2_L.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2_L.setText("Welcome To Compact Taxing - A Tax Management System");

        username_L.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        username_L.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        salary_L.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        salary_L.setText("Salary Certificate");

        s_upload_B.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        s_upload_B.setText("Upload");
        s_upload_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_upload_BActionPerformed(evt);
            }
        });

        bank_L2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bank_L2.setText("Bank Statement");

        b_upload_B2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        b_upload_B2.setText("Upload");
        b_upload_B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_upload_B2ActionPerformed(evt);
            }
        });

        chalan_L3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chalan_L3.setText("Chalan Copy");

        c_upload_B3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        c_upload_B3.setText("Upload");
        c_upload_B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_upload_B3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(username_L, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(title2_L, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10))
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(salary_L)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(s_upload_B))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bank_L2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(b_upload_B2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chalan_L3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(c_upload_B3)))
                                .addGap(195, 195, 195))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(title2_L, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(username_L, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salary_L)
                            .addComponent(s_upload_B))
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bank_L2)
                            .addComponent(b_upload_B2))
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chalan_L3)
                            .addComponent(c_upload_B3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myprofile_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myprofile_BActionPerformed
        // TODO add your handling code here:
        HomeController profile = new HomeController();
        profile.open();
        //setVisible(false);
    }//GEN-LAST:event_myprofile_BActionPerformed

    private void receipt_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receipt_BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receipt_BActionPerformed

    private void logout_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_BActionPerformed
        int rst = JOptionPane.showConfirmDialog(null, "Are you sure want to logout");
        if (rst == 1 || rst == 2){
            
        }
        else{
            User_LoginView user = new User_LoginView();
            setVisible(false);
            user.setVisible(true);
        }
    }//GEN-LAST:event_logout_BActionPerformed

    private void s_upload_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_upload_BActionPerformed
        JFileChooser j = new JFileChooser();
        j.showSaveDialog(null);
    }//GEN-LAST:event_s_upload_BActionPerformed

    private void b_upload_B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_upload_B2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_upload_B2ActionPerformed

    private void c_upload_B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_upload_B3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_upload_B3ActionPerformed

    private void hone_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hone_BActionPerformed
        setVisible(false);
    }//GEN-LAST:event_hone_BActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_DocumentsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_DocumentsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_DocumentsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_DocumentsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_DocumentsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appoinment_B;
    private javax.swing.JButton b_upload_B2;
    private javax.swing.JLabel bank_L2;
    private javax.swing.JButton c_upload_B3;
    private javax.swing.JLabel chalan_L3;
    private javax.swing.JLabel home_L;
    private javax.swing.JButton hone_B;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton logout_B;
    private javax.swing.JButton mydoc_B;
    private javax.swing.JButton myprofile_B;
    private javax.swing.JButton payment_B;
    private javax.swing.JButton receipt_B;
    private javax.swing.JButton s_upload_B;
    private javax.swing.JLabel salary_L;
    private javax.swing.JLabel title2_L;
    private javax.swing.JLabel title_L;
    private javax.swing.JLabel username_L;
    // End of variables declaration//GEN-END:variables
}
